### ISSUE TITLE
Download - LinTO Doc

### ISSUE THREAD

**Issue by damienlaine** [linto-ai/documentation-website#32]
https://doc.linto.ai/#/services/linstt_download 

 Description

**Comment by fred3ric** [comment]
Hi, congrats for the impressive model you provide on this page. I wonder if you have any advice to add new words to the linSTT_AM_fr-FR_v2.0.0 model and use it on vosk-api ? I did try to follow the tuto on this reference (https://chrisearch.wordpress.com/2017/03/11/speech-recognition-using-kaldi-extending-and-using-the-aspire-model/)  and to adapt with your model. Unfortunately, I cannot find the way to merge the 'lm_unpruned' with the dict generated with new words (chapter:  Merging the input files). Do you provide any support on this ? thank you, Frederic

**Comment by irebai** [comment]
Hi Frederic,
I would like to thank you for your consideration of our work and our models.
If you want to use our models, we have already a transcription service (https://github.com/linto-ai/linto-platform-stt-standalone-worker) which is based on vosk-api.
To adapt our models to new language model, you can use our service manager (https://github.com/linto-ai/linto-platform-stt-service-manager) but this service gives the ability to create new model without merging it with the existing one.
We could make a meeting point to discuss about this in more detail.
Contact me at: irebai@linagora.com
Cordially, Ilyes.

**Comment by sravani40** [comment]
can i know by using which source phonemes are generated for french language for your models?
